In [5]:
import torch
import numpy


In [4]:
print(torch.__version__)

2.3.0.post101


In [5]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [29]:
# Scalars
s1 = torch.tensor(5)
print("the tensor is {} :".format(s1))
print(s1)

the tensor is 5 :
tensor(5)


In [21]:
type(s1)
type(s1) is torch.Tensor

True

In [30]:
# checking its dimension and shape
s1.ndim, s1.shape

(0, torch.Size([]))

In [293]:
# getting tensor object back to python object
s1.item() , type(s1.item())

(7, int)

In [42]:
# tensor
# torch.Tensor.size() produces the same result as torch.Tensor.shape attribute
v1 = torch.tensor([7,7])
print(f"The tensor v1 : {v1}")
print(f"Number of dimensions: {v1.ndim}")
print(f"Shape of the tensor: {v1.shape}, {v1.size()}")

The tensor v1 : tensor([7, 7])
Number of dimensions: 1
Shape of the tensor: torch.Size([2]), torch.Size([2])


In [41]:
v2 = torch.tensor([[7,7]])
print(f"The tensor v2 : {v2}")
print(f"Number of dimensions: {v2.ndim}")
print(f"Shape of the tensor: {v2.shape}")

The tensor v2 : tensor([[7, 7]])
Number of dimensions: 2
Shape of the tensor: torch.Size([1, 2])


In [39]:
v3 = torch.tensor([[7],[7]])
print(f"The tensor v3 : \n{v3}")
print(f"Number of dimensions: {v3.ndim}")
print(f"Shape of the tensor: {v3.shape}")

The tensor v3 : 
tensor([[7],
        [7]])
Number of dimensions: 2
Shape of the tensor: torch.Size([2, 1])


In [37]:
v4 = torch.tensor([[7, 7],
                   [8, 8]])
print(f"The tensor v4 :\n{v4}")
print(f"Number of dimensions: {v4.ndim}")
print(f"Shape of the tensor: {v4.shape}")


The tensor v4 :
tensor([[7, 7],
        [8, 8]])
Number of dimensions: 2
Shape of the tensor: torch.Size([2, 2])


In [35]:
t1 = torch.tensor([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(f"The tensor t1 : \n{t1}")
print(f"Number of dimensions: {t1.ndim}")
print(f"Shape of the tensor: {t1.shape}")


The tensor t1 : 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Number of dimensions: 2
Shape of the tensor: torch.Size([3, 3])


In [36]:
t2 = torch.tensor([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]])

print(f"The tensor t2 :\n{t2}")
print(f"Number of dimensions: {t2.ndim}")
print(f"Shape of the tensor: {t2.shape}")

The tensor t2 :
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Number of dimensions: 3
Shape of the tensor: torch.Size([1, 3, 3])


### Random tensors


In [63]:
# torch.rand(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False)
# Returns a tensor filled with random numbers from a uniform distribution on the interval 
# size (int...) – a sequence of integers defining the shape of the output tensor. Can be a variable number of arguments or a collection like a list or tuple.
randomtensor = torch.rand(4, 5)
randomtensor

tensor([[0.6087, 0.5233, 0.1149, 0.0368, 0.7338],
        [0.5498, 0.5969, 0.1499, 0.2130, 0.4098],
        [0.7339, 0.2757, 0.2997, 0.0635, 0.2213],
        [0.1771, 0.7873, 0.9100, 0.7303, 0.7664]])

In [65]:
randomtensor1 = torch.rand(4)
print(randomtensor1)
randomtensor1.ndim, randomtensor1.shape


tensor([0.9872, 0.7433, 0.1704, 0.9001])


(1, torch.Size([4]))

In [62]:
randomtensor2 = torch.rand(size=(224, 224, 3))
randomtensor2.ndim, randomtensor2.shape

(3, torch.Size([224, 224, 3]))

In [102]:
# torch.randn(*size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False)
# Returns a tensor filled with random numbers from a normal distribution with mean 0 and variance 1 (also called the standard normal distribution).
# size (int...) – a sequence of integers defining the shape of the output tensor. Can be a variable number of arguments or a collection like a list or tuple.
randomtensor5 = torch.randn(6)
randomtensor5


tensor([ 1.9283,  0.9503,  0.1671, -1.2486, -0.3766, -0.4467])

### Tensors of all zeros and ones

In [71]:
zerostensor = torch.zeros(size=(3, 4))
zerostensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [75]:
onestensor = torch.ones(size=(3, 4))
onestensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [77]:
# datatype of tensors
onestensor.dtype, type(onestensor)

(torch.float32, torch.Tensor)

In [78]:
randomtensor.dtype

torch.float32

#### Identity matrix

### Creating tensors of a particular range

In [79]:
# torch.arange(start=0, end, step=1, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
rangetensor = torch.arange(5)
rangetensor

tensor([0, 1, 2, 3, 4])

In [83]:
rangetensor1 = torch.arange(0,5,2)
rangetensor1

tensor([0, 2, 4])

### Creating tensors of the same size as other tensors

In [85]:
# torch.zeros_like(input, *, dtype=None, layout=None, device=None, requires_grad=False, memory_format=torch.preserve_format)
# input (Tensor) – the size of input will determine size of the output tensor.
liketensor = torch.zeros_like(input=randomtensor)
liketensor


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [86]:
liketensor1 = torch.zeros_like(input=randomtensor, dtype=torch.float16, device='cpu')
liketensor1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float16)

In [87]:
liketensor2 = torch.ones_like(input=randomtensor)
liketensor2

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

### Tensor Indexing and Slicing 

In [67]:
# Manipulating a 2d tensor using indexing
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(a[:,[1,0,2]])

tensor([[2, 1, 3],
        [5, 4, 6]])


In [72]:
# Boolean indexing
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(a[(a.sum(axis=1)>7),:])


tensor([[4, 5, 6]])


In [68]:
# Slicing
# Create a 2D tensor
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(a[1]) # accessing the second element of the first dimension
print(a[0]) # accessing the first element of the first dimension
print(a[0,1]) # accessing the element of the second dimension of the first element of the first dimension
print(a[0:1,1:2])

tensor([4, 5, 6])
tensor([1, 2, 3])
tensor(2)
tensor([[2]])


In [66]:
# create a 3 D tensor
a = torch.tensor([[[1, 2, 3, 4, 5, 6, 7, 8],
                   [10, 11, 12, 13, 14, 15, 16, 17]],
                  [[18, 19, 20, 21, 22, 23, 24, 25],
                   [26, 27, 28, 29, 30, 31, 32, 33]]]) 

print(a[0])
print(a[1:,1:])
print(a[0:,1])
print(a[[0,1],1]) # this produces same output as the above statement 


tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [10, 11, 12, 13, 14, 15, 16, 17]])
tensor([[[26, 27, 28, 29, 30, 31, 32, 33]]])
tensor([[10, 11, 12, 13, 14, 15, 16, 17],
        [26, 27, 28, 29, 30, 31, 32, 33]])
tensor([[10, 11, 12, 13, 14, 15, 16, 17],
        [26, 27, 28, 29, 30, 31, 32, 33]])


In [ ]:
# torch.tensor() always copies data. If you have a Tensor data and just want to change its requires_grad flag, use requires_grad_() or detach()or to avoid a copy. If you have a numpy array and want to avoid a copy, use torch.as_tensor().


In [123]:
ten = torch.tensor([1.0,2.0,3.0])

In [124]:
torch.tensor(ten, requires_grad=True)

/var/folders/s6/7qcpm9193z3dpfcptl5y21hw0000gn/T/ipykernel_5132/4081231999.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.tensor(ten, requires_grad=True)


tensor([1., 2., 3.], requires_grad=True)

In [128]:
ten.requires_grad_(True)
ten.requires_grad

True

In [204]:
nparr= np.random.rand(4,2)
nparr

array([[0.3303113 , 0.13759222],
       [0.30192778, 0.8054955 ],
       [0.29949424, 0.93748183],
       [0.23748336, 0.81422569]])

In [194]:
ten2 = torch.tensor(nparr)
ten2

tensor([[0.1060, 0.6426],
        [0.1599, 0.7441],
        [0.6014, 0.2814],
        [0.4579, 0.3772]], dtype=torch.float64)

In [195]:
ten2[0][1] = 90
nparr

array([[0.10599141, 0.6426084 ],
       [0.15986856, 0.74414196],
       [0.60142378, 0.2813948 ],
       [0.45789426, 0.37723962]])

In [183]:
ten2[2][1]= 25
nparr

array([[0.6499145 , 0.86795959],
       [0.95124702, 0.83439964],
       [0.12134   , 0.31840162],
       [0.8089194 , 0.22840108]])

In [205]:
ten3 =torch.as_tensor(nparr)
ten3


tensor([[0.3303, 0.1376],
        [0.3019, 0.8055],
        [0.2995, 0.9375],
        [0.2375, 0.8142]], dtype=torch.float64)

In [206]:
ten3[0][1]= 15

In [203]:
nparr

array([[0.01779952, 0.07730633],
       [0.98869322, 0.17180187],
       [0.66388058, 0.38763681],
       [0.53668414, 0.0094481 ]])

In [210]:
tensorr = torch.tensor([3,4,5])
tensorr.to(torch.float32)

tensor([3., 4., 5.])

### Tensors datatypes and device and operations

#### Tensor datatype

In [261]:
# defauft datatype in pytorch is float32
tensor1 = torch.tensor([8.0, 9.0, 10.0],
                       dtype=None,
                       device=None,
                       requires_grad=False)
tensor1 , tensor1.dtype


(tensor([ 8.,  9., 10.]), torch.float32)

In [262]:
tensor2 = tensor1.type(torch.float16)
tensor2

tensor([ 8.,  9., 10.], dtype=torch.float16)

In [263]:
# We can also use torch.Tensor.to() to change the dtype
# torch.Tensor.to() returns the same tensor if no change has been made(correct dtype and device). Otherwise, it returns a copy of the tensor with the new specified dtype
tensor3 = torch.tensor([4, 5 , 9])
print(f"The tensor has dtype : {tensor3.dtype}")
tensor4 = tensor3.to(torch.float16)
print(f"The tensor has dtype : {tensor4.dtype}")

The tensor has dtype : torch.int64
The tensor has dtype : torch.float16


#### Tensor Device

In [264]:
# device
# torch.Tensor.to() returns the same tensor if no change has been made(correct device and dtype). Otherwise, it moves the tensor to the new specified device and dtype
tensor5 = torch.tensor([4, 5 , 9])
print(f"The tensor is on : {tensor5.device }")
tensor6 = tensor5.to(torch.device("cuda"))
print(f"The tensor is on: {tensor6.device}")

The tensor is on : cpu


AssertionError: Torch not compiled with CUDA enabled

In [ ]:
# torch.Tensor.cuda() or torch.Tensor.cpu() can be used  to do the same thing

tensor7 = torch.tensor([3.0, 4.0, 5.0])
print(f" The tensor is on: {tensor7.device}")
tensor8 = tensor7.cuda()
print(f"The tensor is on: {tensor8.device}")

 The tensor is on: cpu


AssertionError: Torch not compiled with CUDA enabled

##### Note: The method .to() performs an inplace operation with models. We will see more about this later.

#### Tensor Operations

In [ ]:
# addition 
mytensor = torch.tensor([4, 5 ,6])
mytensor + 5

tensor([ 9, 10, 11])

In [ ]:
# multiplication 
mytensor * 10

tensor([40, 50, 60])

In [ ]:
# subtraction 
mytensor - 2

tensor([2, 3, 4])

In [ ]:
# element wise addition of 2 tensors
mytensor2 = torch.tensor([7, 8, 9])
print(f"addition of 2 tensors: {mytensor} + {mytensor2}")
print(mytensor + mytensor2)

addition of 2 tensors: tensor([4, 5, 6]) + tensor([7, 8, 9])
tensor([11, 13, 15])


In [ ]:
# pytorch inbuilt functions for manipulating tensors
print(torch.add(mytensor, 10))
print(torch.mul(mytensor,5))


tensor([14, 15, 16])
tensor([20, 25, 30])


In [280]:
# Matrix multiplication
# using pytorch inbuilt function
print(torch.matmul(mytensor,mytensor2).dtype)

# using matrix multiplication operator
print(mytensor @ mytensor2)

torch.int64
tensor(122)


#### Tensor aggregation
##### min, max, mean, sum of the whole tensor or across different rows or columns of the tensor)

In [270]:
mytensor4 = torch.arange(10,190,30)
mytensor4

tensor([ 10,  40,  70, 100, 130, 160])

In [294]:
print(f"Minimum value in the tensor: {mytensor4} is {mytensor4.min()}")

# We also have Pytorch inbuilt function to do that
print(f"Minimum value in the tensor: {mytensor4} is {torch.min(mytensor4)}")


Minimum value in the tensor: tensor([ 10,  40,  70, 100, 130, 160]) is 10
Minimum value in the tensor: tensor([ 10,  40,  70, 100, 130, 160]) is 10


In [298]:
mytensor4.max(), torch.max(mytensor4)

(tensor(160), tensor(160))

In [306]:
# pytorch inbuilt function mean() and torch.Tensor.mean() method expects input of either a floating point datatype or complex datatype

print( "mean of the tensor:", mytensor4.to(torch.float32).mean())
print( "mean of the tensor:", torch.mean(mytensor4.to(torch.float32)))

mean of the tensor: tensor(85.)
mean of the tensor: tensor(85.)


In [307]:
mytensor4.sum() , torch.sum(mytensor4)

(tensor(510), tensor(510))

In [309]:
# argmin() and argmax() methods
# Return the index of the minimum and maximum value of the tensor respectively
print("Index of min value:", mytensor4.argmin())
print("Index of max value:", mytensor4.argmax())


Index of min value: tensor(0)
Index of max value: tensor(5)


In [ ]:
# transpose of a tensor
mytensor3 = torch.tensor([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9],
                          [10, 11, 12]])

print(f"Original Tensor: \n{mytensor3}, \nTransposed Tensor: \n{mytensor3.T}")
print(f"Shape of original tensor: {mytensor3.shape},\nShape of transposed tensor: {mytensor3.T.shape}")

### Tensor Manipulation

#### Different methods to manipulate tensors:
#### Unsqueeze, Squeeze

In [89]:
# Adding a new dimension to a tensor
x = torch.randn(5)
print("Original Tensor:", x)
print("Reshaped tensor shape:", x[None,:].shape)
print("Reshaped tensor:",x[None,:])


Original Tensor: tensor([ 1.0933, -0.1564, -0.8223,  2.6266, -0.6616])
Reshaped tensor shape: torch.Size([1, 5])
Reshaped tensor: tensor([[ 1.0933, -0.1564, -0.8223,  2.6266, -0.6616]])


In [101]:
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])

print(x.shape)
print(x[:,None].shape)
print(x[:,None,:].shape)
print(x[...,None].shape)
print(x[None,:].shape)

torch.Size([3, 2])
torch.Size([3, 1, 2])
torch.Size([3, 1, 2])
torch.Size([3, 2, 1])
torch.Size([1, 3, 2])


In [105]:
# Adding a new dimension to a tensor using torch.Tensor.unsqueeze()
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])

print(x.shape)
print(x.unsqueeze(1).shape)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(2).shape)

# The output tensor shares memory with the orginal tensor, so changing its contents will change the contents of the original tensor.
t = x.unsqueeze(2)
t[2,0]=15
x

torch.Size([3, 2])
torch.Size([3, 1, 2])
torch.Size([1, 3, 2])
torch.Size([3, 2, 1])


tensor([[ 1,  2],
        [ 3,  4],
        [15,  6]])

In [112]:
# Removing dimensions of size 1 from a tensor.
# torch.Tensor.squeeze(dim=None), or torch.squeeze(tensor, dim=None) returns a tensor with all specified dimensions of input of size 1 removed.
# The output tensor shares memory with the orginal tensor,so changing the contents of one will change the contents of the other.

x = torch.randn(2,4,1,3)

print(f"Original shape of tensor x: {x.shape}")
print(f"Shape of squeezed tensor x : {x.squeeze().shape}")

y = torch.randn(2,1,4,1,3,1)

print(y.squeeze().shape)
print(y.squeeze(4).shape) # We can also specify the dimension on which we want to perform squeeze operation
print(y.squeeze((3,5)).shape) # tuple of ints (dimenions) can also be passed

Original shape of tensor x: torch.Size([2, 4, 1, 3])
Shape of squeezed tensor x : torch.Size([2, 4, 3])
torch.Size([2, 4, 3])
torch.Size([2, 1, 4, 1, 3, 1])
torch.Size([2, 1, 4, 3])


#### View, Reshape, Permute

In [137]:
# torch.Tensor.view() returns a view of the tensor with the same number of elements and specified shape
# The viewed tensor shares memory with the original tensor if the new view size is compatible with its original size and stride. 
# For more information, refer: https://pytorch.org/docs/stable/generated/torch.Tensor.view.html#torch.Tensor.view

x = torch.randn(2,4,1,3)
print("Shape of tensor x:",x.shape)
print("Shape of view of tensor x:",x.view(8,3).shape)  #returning a view


Shape of tensor x: torch.Size([2, 4, 1, 3])
Shape of view of tensor x: torch.Size([8, 3])
tensor([[[[ 0.2541, -0.2963, -2.7909]],

         [[-1.0001,  1.7217, -1.2879]],

         [[-0.0036, -0.2732,  1.2095]],

         [[ 0.3788, -0.9017, -0.3504]]],


        [[[-0.6296, -0.3684,  1.2024]],

         [[ 0.2568,  0.7578, -2.0405]],

         [[-0.9594,  1.4222,  1.2166]],

         [[ 1.0098, -0.9031,  0.1935]]]])
tensor([[ 0.2541, -0.2963, -2.7909],
        [-1.0001,  1.7217, -1.2879],
        [-0.0036, -0.2732,  1.2095],
        [ 0.3788, -0.9017, -0.3504],
        [-0.6296, -0.3684,  1.2024],
        [ 0.2568,  0.7578, -2.0405],
        [-0.9594,  1.4222,  1.2166],
        [ 1.0098, -0.9031,  0.1935]])


In [206]:
# If the new view size of the tensor is not compatible with its original size and stride, it doesnt return a copy.

x = torch.ones(4,2)
y = x.T

print(f"Size of the tensor y: {x.T.shape}")
print(f"View of the tensor y: {y.view(8)}")



Size of the tensor y: torch.Size([2, 4])


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [171]:
# However, in this case the new view size is compatible with original size and stride of original tensor y
z = y.view(2,2,2)
print(f"Size of the tensor y: {y.shape}")
print(f"View of the tensor y: \n{y.view(2,2,2)}")
print(f"Another View of the tensor y: \n{y.view(1,2,4)}")

Size of the tensor y: torch.Size([2, 4])
View of the tensor y: 
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
Another View of the tensor y: 
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [172]:
# It returns a copy of the tensor if the dtype is changed

x = torch.ones(4,2)
print(y)
y[0,2]=1000
print(x)       # changing y won't change x as y is a copy of x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [210]:
# torch.reshape() or torch.Tensor.reshape() returns a tensor of the specified shape with same number of elements
# It would return a view if the tensor is contiguous in memory or it has compatible strides with the new tensor. Otherwise, it returns a copy.
# For more information, refer: https://pytorch.org/docs/stable/generated/torch.reshape.html 

a = torch.arange(0,120,10)
print("Shape of original tensor a :",a.shape)
b = a.reshape(6,2,1)
print("Shape of reshaped tensor b :",b.shape)

Shape of original tensor a : torch.Size([12])
Shape of reshaped tensor b : torch.Size([6, 2, 1])


In [211]:
print("Original tensor:",a)
c = a.reshape(-1)   # returns same output as a.ravel()
print(f"Shape of reshaped tensor c : \n {c ,c.shape}")

# The reshape operation returned a copy of tensor 'a' here
c[4]=500
print("Tensor a after making changes to c :",a)  

Original tensor: tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])
Shape of reshaped tensor c : 
 (tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110]), torch.Size([12]))
Tensor a after making changes to c : tensor([  0,  10,  20,  30, 500,  50,  60,  70,  80,  90, 100, 110])


In [372]:
# torch.permute(tensor,dims) returns a view of the original tensor input with its dimensions permuted.

x = torch.randn(2,5,6)
y = torch.permute(x,(1,0,2))
print(f"Shape of permuted tensor: {y.shape}")
y[1,1,4] = 500
print(x)    # changing y changed x because y is a view of x


Shape of permuted tensor: torch.Size([5, 2, 6])
tensor([[[ 4.5720e-01, -1.0126e+00,  1.1294e+00, -5.3137e-01, -2.9312e-01,
          -1.5121e+00],
         [-1.2418e+00,  5.9366e-01,  7.5422e-01, -1.3300e+00,  2.2546e-01,
           1.1712e+00],
         [-7.1094e-01, -1.9538e-01,  7.7954e-01,  1.4606e+00, -5.3996e-01,
           2.0702e+00],
         [-3.7673e-01, -1.1635e+00, -9.1467e-01, -1.3022e+00,  6.3097e-01,
          -1.0537e+00],
         [-9.3186e-01, -9.0685e-01, -3.9013e-01,  1.0973e+00,  8.1775e-01,
          -1.0055e+00]],

        [[-1.0397e+00, -1.3099e+00, -5.9131e-01, -4.7568e-01, -1.1170e+00,
           4.5954e-01],
         [-1.8662e-01,  2.6337e-01,  2.1734e-01, -6.4150e-01,  5.0000e+02,
          -7.5831e-01],
         [-6.9555e-01, -4.3822e-01, -3.5042e-01,  1.1488e+00,  9.6820e-02,
          -5.0933e-02],
         [-7.7472e-01, -6.9112e-01, -5.9988e-01,  7.8703e-01, -2.2881e+00,
          -8.1541e-01],
         [ 1.6293e-01, -1.1879e-02,  1.7112e+00, -8.3792e-0

#### Flatten, Ravel

In [238]:
# torch.Tensor.flatten() returns a flattened tensor.
# It returns a view if the tensor is contiguous in memory or the new view size is compatible with size and stride of original tensor. Otherwise returns a copy
# If parameters start_dim and end_dim are passed, it flattens only the dimensions starting from start_dim to end_dim

x = torch.tensor([[[2, 3, 4],
                   [5, 6, 7]],
                  [[8, 9, 10],
                  [11, 12, 13]]])

y = x.flatten()   # Returned a view
print("Flattened tensor :",y)
y[0]=200
print("Changes made in x when y is changed:\n", x)  



Flattened tensor : tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
Changes made in x when y is changed: 
 tensor([[[200,   3,   4],
         [  5,   6,   7]],

        [[  8,   9,  10],
         [ 11,  12,  13]]])


In [226]:
# using parameter start_dim
x = torch.tensor([[[2, 3, 4],
                   [5, 6, 7]],
                  [[8, 9, 10],
                  [11, 12, 13]]])

y = x.flatten(start_dim=1)
print(y)



tensor([[ 2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13]])


True

In [243]:
a = torch.ones(2,4)
b = a.T
c = b.flatten()  # a copy is created
c[0]=10
print(a)  # changes are not reflected in tensor a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [214]:
# Flattening a zero-dimensional tensor will return a one-dimensional view.
a = torch.tensor(4)
print("Original tensor dimensions:", a.ndim)
b = a.flatten()
print("Flattened tensor dimensions:", b.ndim)

Original tensor dimensions: 0
Flattened tensor dimensions: 1


In [244]:
# torch.Tensor.ravel() returns a contiguous flattened tensor
# Returns a view if the tensor is contiguous in memory or the new view size is compatible with the size and stride of original tensor. Otherwise, returns a copy

x = torch.randn(3,2)
y = x.ravel()   # x.reshape(-1) will result in the same output
print(y)



tensor([ 0.8524, -0.8937,  0.9879,  0.5301,  1.0332,  0.5526])


#### Stack, hstack, vstack, concatenate

In [296]:
# torch.stack(tesnors, dim=0) concatenates a sequence of tensors along a new dimension. All the tensor need to be of the same size.
# dim should be between -(n+1) to n+1, where is the no. of dimensions of the tensors

x = torch.randn(2, 3)
print(f"Shape of new stacked tensor1 :", torch.stack((x,x),1).shape)
print(f"Shape of new stacked tensor2 :", torch.stack((x,x,x,x),2).shape)
print(f"Shape of new stacked tensor3 :", torch.stack((x,x),-3).shape)

Shape of new stacked tensor1 : torch.Size([2, 2, 3])
Shape of new stacked tensor2 : torch.Size([2, 3, 4])
Shape of new stacked tensor3 : torch.Size([2, 2, 3])


In [313]:
# torch.hstack() stacks tensors in sequence horizontally (column wise).
# concatenates along the first axis for 1-D tensors, and along the second axis for all other tensors.

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
c = torch.hstack((a,b))
print(f"New stacked tensor : {c} , Size: {c.shape}")

New stacked tensor : tensor([1, 2, 3, 4, 5, 6]) , Size: torch.Size([6])


In [314]:
a = torch.rand(2,3)
b = torch.rand(2,3)
c = torch.hstack((a,b))
print(f"New stacked tensor :\n{c} , \nSize: {c.shape}")

New stacked tensor :
tensor([[0.9835, 0.3310, 0.3619, 0.5234, 0.9089, 0.1942],
        [0.0959, 0.6794, 0.3940, 0.6908, 0.1097, 0.9669]]) , 
Size: torch.Size([2, 6])


In [312]:
a = torch.rand(2,3,4,5)
b = torch.rand(2,3,4,5)
c = torch.hstack((a,b))
print(f"New stacked tensor Size: {c.shape}")

New stacked tensor Size: torch.Size([2, 6, 4, 5])


In [320]:
# torch.vstack() stacks tensors in sequence vertically (row wise).
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
c = torch.vstack((a,b))
print(f"New stacked tensor : \n{c}")
print(f"Size: {c.shape}")

New stacked tensor : 
tensor([[1, 2, 3],
        [4, 5, 6]])
Size: torch.Size([2, 3])


In [321]:
a = torch.rand(2,3,4,5)
b = torch.rand(2,3,4,5)
c = torch.vstack((a,b))
print(f"New stacked tensor Size: {c.shape}")

New stacked tensor Size: torch.Size([4, 3, 4, 5])


In [293]:
# torch.cat(tensors, dim=0) concatenates the given tensors along an existing dimension.
# All tensors must either have the same shape (except in the concatenating dimension) or be a 1-D empty tensor with size (0,).
# dim : dimesion over which tensors are to be concatenated

x = torch.randn(2, 3)
y = torch.rand(2,3)
print(f"Shape of new concatenated tensor1 :", torch.cat((x,y),0).shape)



Shape of new concatenated tensor1 : torch.Size([4, 3])


In [294]:
# Same shape except in the concatenating dimension
x = torch.randn(2, 3)
y = torch.rand(4,3)
print(f"Shape of new concatenated tensor2 :", torch.cat((x,y),0).shape)

Shape of new concatenated tensor2 : torch.Size([6, 3])


In [295]:
x = torch.randn(2, 3)
a = torch.tensor([])    # Empty tensor with size 0
print(f"Shape of new concatenated tensor3 :", torch.cat((x,a),0).shape)
x.shape

Shape of new concatenated tensor3 : torch.Size([2, 3])


torch.Size([2, 3])

#### Repeat, Expand ,repeat_interleave

In [367]:
# torch.Tensor.repeat(sizes) repeats the tensor along the specified dimensions.
# sizes : The no. of times to repeat this tensor along the specified dimensions.

x = torch.tensor([1, 2, 3])
print(f"Repeated tensor1: \n{x.repeat(4, 2)}, shape:{x.repeat(4, 2).shape}")  # repeats the tensor x 4 times in the first dim and twice in the second dim
print(f"Repeated tensor2: \n{x.repeat(4, 2, 1)}, shape:{x.repeat(4, 2, 1).shape}") 


Repeated tensor1: 
tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]]), shape:torch.Size([4, 6])
Repeated tensor2: 
tensor([[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]]), shape:torch.Size([4, 2, 3])


In [332]:
# torch.repeat_interleave(input,repeats,dim=None) repeats elements of a tensor
# inputs : The input tensor
# repeats : can be a tensor or int, it specifies the no. of repetitions for each element
# dim : The dim along which repetition will be done. If not provided, it uses a flattened i/p array and returns a flat o/p array.

x = torch.tensor([1, 2, 3])
print(f"Repeated tensor: \n{torch.repeat_interleave(x,2)}")

Repeated tensor: 
tensor([1, 1, 2, 2, 3, 3])


In [334]:
x = torch.tensor([[1, 2],
                 [3, 4]])
print(f"Repeated tensor: \n{torch.repeat_interleave(x,2)}")

Repeated tensor: 
tensor([1, 1, 2, 2, 3, 3, 4, 4])


In [335]:
x = torch.tensor([[1, 2],
                 [3, 4]])
print(f"Repeated tensor: \n{torch.repeat_interleave(x,2,1)}")

Repeated tensor: 
tensor([[1, 1, 2, 2],
        [3, 3, 4, 4]])


In [341]:
x = torch.tensor([[1, 2, 3],
                 [3, 4, 7]])
print(f"Repeated tensor: \n{torch.repeat_interleave(x,torch.tensor([2,1,3]),1)}")

Repeated tensor: 
tensor([[1, 1, 2, 3, 3, 3],
        [3, 3, 4, 7, 7, 7]])


In [365]:
# torch.Tensor.expand(sizes) returns a new view of the tensor with singleton dimensions expanded to a larger size.
# sizes: the desired expanded size, -1 when no change in size of dimension is needed

a = torch.tensor([[1, 2, 3]]) # size is 1x3
a.expand(4,3)  # changing the singleton dimension (here it is  first dimension) to 4

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

### Numpy array to Pytorch Tensor

In [392]:
# torch.from_numpy() creates a torch tensor from a numpy ndarray. 
# The returned tensor shares same memory as the numpy array, if the dtype remains same as the input numpy array and is on the same device(cpu)

array = np.arange(1.0, 10.0)
tensor = torch.from_numpy(array)
tensor[0]= 500
print(array)



[500.   2.   3.   4.   5.   6.   7.   8.   9.]


In [385]:
# if we change the dtype, the changes will not be reflected back 
array = np.arange(1.0, 10.0)
tensor = torch.from_numpy(array).to(torch.float32)
tensor[0]= 500
print(array)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [386]:
# torch.as_tensor(data, dtype=None, device=None) converts data into a tensor, sharing data and preserving autograd history if possible.
# the data could be a tensort, list, tuple, scalar or numpy array
# if the data is a tensor with the requested dtype and device, it returns the same tensor with the autograd history . Otherwise, it returns a copy.
# For tensors, same can be done with the torch.tensor() function but it always creates a copy.
# if the data is a numpy array with the requested dtype and the same device, the output tensor shares memory with the array. Otherwise, it returns a copy of it.

array = np.arange(1.0, 10.0)
tensor = torch.as_tensor(array)
tensor[0]= 500
print(array)

[500.   2.   3.   4.   5.   6.   7.   8.   9.]


In [387]:
array = np.arange(1.0, 10.0)
tensor = torch.as_tensor(array, dtype=torch.float32) # now this will create a copy because dtype has been changed
tensor[0]= 500
print(array)   # changes are not reflected back in the array

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


### Pytorch tensor to Numpy array

In [395]:
# torch.Tensor.numpy(force=False) converts a tensor into a numpy array
tensor = torch.tensor([1, 2, 3])
nparray = tensor.numpy()
nparray[0] = 1000
tensor

tensor([1000,    2,    3])

In [396]:
# If force is False (the default), the conversion is performed only if the tensor is on the CPU, does not require grad, does not have its conjugate bit set, and is a dtype and layout that NumPy supports. The returned ndarray and the tensor will share their storage, so changes to the tensor will be reflected in the ndarray and vice versa.
tensor = torch.tensor([1, 2, 3]).to(device='cuda')
nparray = tensor.numpy()


AssertionError: Torch not compiled with CUDA enabled

In [398]:
tensor = torch.tensor([1, 2, 3], requires_grad=True)
nparray = tensor.numpy()

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [397]:
# If force is True this is equivalent to calling t.detach().cpu().resolve_conj().resolve_neg().numpy(). If the tensor isn’t on the CPU or the conjugate or negative bit is set, the tensor won’t share its storage with the returned ndarray. 
tensor = torch.tensor([1, 2, 3]).to(device='cuda')
nparray = tensor.numpy(force=True)



AssertionError: Torch not compiled with CUDA enabled

#### Reproducibility

In [401]:
# Random seed
# Random seed or seed is a number(or vector) used to initialize a pseudorandom number generator

random_seed = 42
torch.manual_seed(random_seed)
x = torch.randn([1,3])
print(x)

# if a pseudorandom number generator is reinitialized with the same seed, it will produce the same sequence of numbers

torch.manual_seed(random_seed)
y = torch.randn([1,3])
print(y)

tensor([[0.3367, 0.1288, 0.2345]])
tensor([[0.3367, 0.1288, 0.2345]])


### GPU access and devices

In [399]:
# check if gpu is available
torch.cuda.is_available()

False

In [407]:
# setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [404]:
# count the number of devices
print(torch.cpu.device_count())
print(torch.cuda.device_count())

1
0


In [408]:
# Moving the tensors to GPU
# If you haven't defined the device while creating the tensor, you can use torch.Tensor.to() function to move it to the specified device.
# Default device is cpu 

x = torch.tensor([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0]])

y = x.to(device)    # using the device agnostic code to setup the device


In [409]:
torch.__version__

'2.3.1'